---
- name: config vms
  hosts: "{{ servers }}"
  vars_files:
      - config_vars
  tasks:

    - name: install node
      shell: |
          curl -sL "{{ node_js }}" | sudo -E bash - && sudo apt-get install -y nodejs

    - name: Clone a bootcamp-app from github
      git:
        repo: "{{ github_repo }}"
        dest: "{{ repo_path }}"
        clone: yes
        update: yes

    - name: Install packages based on package.json using the npm
      npm:
        path: "{{ repo_path }}"
        state: present

    - name: Copy .env file
      copy:
       src: "{{ path_to_env }}"
       dest: "{{ repo_path }}"
       owner: "{{ owner}}"
       group: "{{ group }}"
       mode: "0644"

    - name: Init database for Bootcamp-app Weight Tracker
      command: npm run initdb
      args:
        chdir: "{{ repo_path }}"

    - name: Start Bootcamp-app Weight Tracker automatically with crontab
      ansible.builtin.cron:
        name: "a job for reboot"
        special_time: reboot
        job: sh -c "cd {{ repo_path }}  && npm run dev"

    - name: reboot the vm's
      become: true
      ansible.builtin.reboot:
