---
- name: config vms
  hosts: all
  vars:
      repo_path: /home/ubuntu/bootcamp-app
      github_repo: https://github.com/alex-1pro/bootcamp-app.git
  tasks:

    - name: install node
      shell: |
          curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - && sudo apt-get install -y nodejs

    - name: Clone a bootcamp-app from github
      git:
        repo: "{{ github_repo }}"
        dest: /home/ubuntu/bootcamp-app
        clone: yes
        update: yes

    - name: Install packages based on package.json using the npm
      npm:
        path: "{{ repo_path }}"
        state: present

    - name: Copy .env file
      copy:
       src: /home/ubuntu/.env
       dest: /home/ubuntu/bootcamp-app
       owner: ubuntu
       group: ubuntu
       mode: "0644"

    - name: Init database for Bootcamp-app Weight Tracker
      command: npm run initdb
      args:
        chdir: "{{ repo_path }}"

    - name: Start Bootcamp-app Weight Tracker automatically with crontab
      ansible.builtin.cron:
        name: "a job for reboot"
        special_time: reboot
        job: sh -c "cd /home/ubuntu/bootcamp-app && npm run dev"

    - name: reboot the vm's
      become: true
      ansible.builtin.reboot:
